"""report_generator.py
Generate CSV and PDF decision support reports, and WhatsApp share links.
Uses fpdf2 for in-memory PDF generation without external binary dependencies.
"""

import csv
import io
import urllib.parse
from datetime import datetime
from fpdf import FPDF


def sanitize_text(text: str) -> str:
    """Sanitize strings for Helvetica Latin-1 PDF output."""
    if text is None:
        return ""
    t = str(text)
    # Replace Rupee symbol and non-latin1 characters
    t = t.replace("₹", "INR ").replace("—", "-").replace("–", "-")
    t = t.replace("🏆", "").replace("🥇", "").replace("🌱", "").replace("🧪", "")
    t = t.replace("☀️", "").replace("🌧", "").replace("⚠️", "").replace("🟢", "").replace("🟡", "").replace("🔵", "")
    return t.encode("latin-1", "replace").decode("latin-1")


def build_report(location, weather, soil, best, alternatives, data_status=None):
    """Return CSV bytes summarizing the decision support recommendation."""
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["=== REAL-TIME SMART AGRICULTURE DECISION SUPPORT REPORT ==="])
    writer.writerow(["Generated At (UTC)", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")])
    writer.writerow([])

    # Data Status Badges
    writer.writerow(["--- DATA STATUS BADGES ---"])
    if data_status:
        for k, v in data_status.items():
            writer.writerow([k, v])
    else:
        writer.writerow(["Status", "Self-Contained Report"])
    writer.writerow([])

    # Location Information
    writer.writerow(["--- LOCATION METADATA ---"])
    writer.writerow(["Location Query / Name", location.get('display_name') if location else 'Manual / Not Specified'])
    writer.writerow(["Latitude", location.get('lat') if location else 'N/A'])
    writer.writerow(["Longitude", location.get('lon') if location else 'N/A'])
    writer.writerow(["District / City", location.get('district') or location.get('city') if location else 'N/A'])
    writer.writerow(["State", location.get('state') if location else 'N/A'])
    writer.writerow(["Country", location.get('country') if location else 'N/A'])
    writer.writerow([])

    # Weather Information
    writer.writerow(["--- WEATHER CONDITIONS ---"])
    for k, v in (weather or {}).items():
        writer.writerow([str(k).replace('_', ' ').title(), v])
    writer.writerow([])

    # Soil Screening Report
    writer.writerow(["--- SOIL HEALTH SCREENING ---"])
    writer.writerow(["Soil Health Score", f"{soil.get('score', 0)}/100"])
    writer.writerow(["Nutrient Overview", ", ".join(soil.get('details', []))])
    writer.writerow(["Strengths", ", ".join(soil.get('strengths', [])) if soil.get('strengths') else "None noted"])
    writer.writerow(["Deficiencies", ", ".join(soil.get('deficiencies', [])) if soil.get('deficiencies') else "None noted"])
    writer.writerow(["Fertilizer Recommendations", ", ".join(soil.get('recommendations', [])) if soil.get('recommendations') else "None"])
    writer.writerow(["Disclaimer", soil.get('disclaimer', "AI-assisted soil screening based on entered values.")])
    writer.writerow([])

    # Best Crop Recommendation
    writer.writerow(["--- TOP RECOMMENDED CROP ---"])
    if isinstance(best, dict):
        for k, v in best.items():
            if k not in ('risk_reasons', 'details'):
                writer.writerow([str(k).replace('_', ' ').title(), v])
        if 'risk_reasons' in best and best['risk_reasons']:
            writer.writerow(["Risk Reasons", "; ".join(best['risk_reasons'])])
    writer.writerow([])

    # Top-5 Crop Comparison Table
    writer.writerow(["--- TOP CROP COMPARISON TABLE ---"])
    if alternatives:
        header = ['Rank', 'Crop', 'AI Confidence (%)', 'Decision Score (/100)', 'Market Price (INR/kg)', 'Market Status', 'Estimated Yield (kg/acre)', 'Revenue (INR)', 'Cost (INR)', 'Profit (INR)', 'ROI (%)', 'Break-even Yield (kg/acre)', 'Risk']
        writer.writerow(header)
        for idx, item in enumerate(alternatives, 1):
            writer.writerow([
                idx,
                item.get('crop', 'N/A'),
                item.get('ai_confidence', item.get('confidence', 'N/A')),
                item.get('decision_score', 'N/A'),
                item.get('market_price', 'N/A'),
                item.get('market_status', 'DEMO'),
                item.get('yield_kg', item.get('yield', 'N/A')),
                item.get('revenue', item.get('income', 'N/A')),
                item.get('cost', 'N/A'),
                item.get('profit', 'N/A'),
                item.get('roi', item.get('profit_margin', 'N/A')),
                item.get('breakeven_yield', 'N/A'),
                item.get('risk', 'N/A'),
            ])
    writer.writerow([])

    writer.writerow(["--- IMPORTANT DISCLAIMER ---"])
    writer.writerow(["Notice", "This report is generated by an AI-assisted Decision Support System for agricultural planning."])
    writer.writerow(["Guidance", "Always verify soil tests in an accredited laboratory and consult local agricultural extension services prior to commercial planting."])

    return output.getvalue().encode('utf-8')


class DecisionPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(16, 185, 129)  # Emerald green
        self.cell(0, 8, "Smart Agriculture Decision Support Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 116, 139)
        self.cell(0, 5, "AI-Powered Multi-Factor Agriculture Intelligence Engine", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(226, 232, 240)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Smart Agriculture DSS - Decision Support Only", align="C")


def build_pdf_report(location, weather, soil, inputs, best, alternatives, timestamp=None) -> bytes:
    """Generate in-memory PDF report bytes using fpdf2."""
    pdf = DecisionPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    ts_str = timestamp or datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Section: Metadata
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 6, sanitize_text(f"Generated Timestamp: {ts_str}"), new_x="LMARGIN", new_y="NEXT")

    loc_name = location.get('display_name') if location else 'Manual / Undetected Location'
    loc_lat = location.get('lat') if location else None
    loc_lon = location.get('lon') if location else None
    coord_str = f" ({loc_lat:.4f}, {loc_lon:.4f})" if loc_lat is not None and loc_lon is not None else ""
    pdf.cell(0, 6, sanitize_text(f"Location: {loc_name}{coord_str}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Section: Weather Summary
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(0, 7, " 1. Weather Summary", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)

    w_dict = weather or {}
    w_mode_label = w_dict.get('weather_source_label') or ("LIVE (Open-Meteo API)" if w_dict.get('is_live') else "MANUAL INPUT")
    temp_val = w_dict.get('temperature', 'N/A')
    hum_val = w_dict.get('humidity', 'N/A')
    eff_rain = w_dict.get('effective_rainfall', w_dict.get('rainfall', 'N/A'))
    act_rain = w_dict.get('actual_rainfall', eff_rain)
    irr_type = w_dict.get('irrigation_type', 'N/A')
    cond_val = w_dict.get('condition', 'N/A')

    if act_rain != 'N/A' and eff_rain != 'N/A' and float(eff_rain) != float(act_rain):
        rain_str = f"Rainfall: {eff_rain} mm (Effective, Actual: {act_rain} mm, Irr: {irr_type})"
    else:
        rain_str = f"Rainfall: {eff_rain} mm"
        if irr_type != 'N/A':
            rain_str += f" (Irr: {irr_type})"

    w_str = f"Source Mode: {w_mode_label}  |  Temp: {temp_val} C  |  Humidity: {hum_val}%  |  {rain_str}  |  Condition: {cond_val}"
    pdf.cell(0, 6, sanitize_text(w_str), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Section: Soil Inputs & Health Screening
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, " 2. Soil Parameters & Health Screening", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)

    inp_dict = inputs or {}
    n_val = inp_dict.get('N', 'N/A')
    p_val = inp_dict.get('P', 'N/A')
    k_val = inp_dict.get('K', 'N/A')
    ph_val = inp_dict.get('ph', 'N/A')
    st_val = inp_dict.get('soil_type', 'Unknown')
    s_score = soil.get('score', 'N/A') if soil else 'N/A'

    soil_str = f"Nutrients: N={n_val}, P={p_val}, K={k_val} kg/ha  |  pH: {ph_val}  |  Soil Type: {st_val}  |  Health Score: {s_score}/100"
    pdf.cell(0, 6, sanitize_text(soil_str), new_x="LMARGIN", new_y="NEXT")

    if soil and soil.get('deficiencies'):
        pdf.cell(0, 6, sanitize_text(f"Deficiencies: {', '.join(soil['deficiencies'])}"), new_x="LMARGIN", new_y="NEXT")
    if soil and soil.get('recommendations'):
        pdf.cell(0, 6, sanitize_text(f"Fertilizer Guidance: {', '.join(soil['recommendations'])}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Section: Top-5 Recommended Crops Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, " 3. Top-5 Recommended Crops Ranking", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(226, 232, 240)
    pdf.cell(10, 6, "Rank", border=1, fill=True)
    pdf.cell(28, 6, "Crop", border=1, fill=True)
    pdf.cell(18, 6, "AI Conf", border=1, fill=True)
    pdf.cell(22, 6, "Score /100", border=1, fill=True)
    pdf.cell(24, 6, "Price (INR)", border=1, fill=True)
    pdf.cell(24, 6, "Yield (kg/ac)", border=1, fill=True)
    pdf.cell(24, 6, "Profit (INR)", border=1, fill=True)
    pdf.cell(18, 6, "ROI", border=1, fill=True)
    pdf.cell(22, 6, "Risk", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 8)
    alts = alternatives or []
    for idx, item in enumerate(alts[:5], 1):
        c_name = str(item.get('crop', 'N/A'))
        conf_str = f"{item.get('ai_confidence', 0)}%"
        sc_str = f"{item.get('decision_score', 0)}"
        p_mkt = item.get('market_price', 0)
        m_stat = item.get('market_status', 'DEMO')
        price_str = f"INR {p_mkt} ({m_stat[:4]})"
        yield_str = f"{item.get('yield_kg', 0)}"
        prof_str = f"INR {item.get('profit', 0):,.0f}"
        roi_str = f"{item.get('roi', 0)}%"
        risk_str = str(item.get('risk', 'N/A'))

        pdf.cell(10, 6, sanitize_text(str(idx)), border=1)
        pdf.cell(28, 6, sanitize_text(c_name), border=1)
        pdf.cell(18, 6, sanitize_text(conf_str), border=1)
        pdf.cell(22, 6, sanitize_text(sc_str), border=1)
        pdf.cell(24, 6, sanitize_text(price_str), border=1)
        pdf.cell(24, 6, sanitize_text(yield_str), border=1)
        pdf.cell(24, 6, sanitize_text(prof_str), border=1)
        pdf.cell(18, 6, sanitize_text(roi_str), border=1)
        pdf.cell(22, 6, sanitize_text(risk_str), border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Section: #1 Recommendation Deep Dive
    if isinstance(best, dict):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, sanitize_text(f" 4. Why #{1} Crop: {best.get('crop', 'Top Crop')}?"), fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, sanitize_text(f"- Highest Decision Support Score: {best.get('decision_score')}/100 with {best.get('ai_confidence')}% ML Confidence"), new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 5, sanitize_text(f"- Estimated Net Profit: INR {best.get('profit'):,.0f} per acre (Calculated ROI: {best.get('roi')}%)"), new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 5, sanitize_text(f"- Risk Level: {best.get('risk')}"), new_x="LMARGIN", new_y="NEXT")
        if best.get('risk_reasons'):
            pdf.cell(0, 5, sanitize_text(f"- Risk Flags: {'; '.join(best['risk_reasons'])}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # Section: Disclaimer
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(220, 38, 38)  # Red accent for disclaimer header
    pdf.cell(0, 6, "Important Disclaimer & Decision Support Policy:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 116, 139)
    disc_text = (
        "This report is generated by an AI-assisted Decision Support System. "
        "It is a decision-support estimate, not a guarantee of crop yield, market price, or net profit. "
        "Always perform laboratory soil testing and consult your local agricultural extension officer before field-level commercial decisions."
    )
    pdf.multi_cell(0, 4, sanitize_text(disc_text))

    return bytes(pdf.output())


def build_whatsapp_share_url(location, weather, soil, best) -> str:
    """Build a pre-filled WhatsApp share link URL."""
    if not best or not isinstance(best, dict):
        return "#"

    crop_name = best.get('crop', 'Recommended Crop')
    ai_conf = best.get('ai_confidence', 0)
    profit = best.get('profit', 0)
    risk = best.get('risk', 'N/A')
    price = best.get('market_price', 0)
    m_stat = best.get('market_status', 'DEMO')

    loc_str = location.get('city') or location.get('name') if location else 'Selected Area'

    summary_text = (
        f"🌱 Smart Crop Recommendation for {loc_str}\n"
        f"🏆 Best Crop: {crop_name} (AI Confidence: {ai_conf}%)\n"
        f"💰 Estimated Profit: ₹{profit:,.0f}/acre | Risk: {risk}\n"
        f"📊 Market Price: ₹{price}/kg ({m_stat})\n"
        f"⚡ Generated by Smart Agriculture DSS"
    )

    encoded_text = urllib.parse.quote(summary_text)
    return f"https://wa.me/?text={encoded_text}"
